<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522041315 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Open job positions for the Team & Career page, seeded with the current listings.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, summary TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');

        // Seed the table with the positions previously hard-coded in the front-end,
        // so the Team & Career page keeps its content and admins have entries to edit.
        $this->addSql(<<<'SQL'
            INSERT INTO job_position (title, location, type, summary, created_at) VALUES
            ('Full-stack Developer (PHP / Vue)', 'Budapest · Hybrid', 'Full-time', 'Build and ship features across our Symfony API and Vue front-end. You will own real product areas from day one.', NOW()),
            ('Sales Representative', 'Budapest · On-site', 'Full-time', 'Help companies discover how HR digitalization makes their teams better — from first contact to signed deal.', NOW()),
            ('Customer Support Specialist', 'Remote', 'Full-time', 'Be the friendly, knowledgeable voice our clients rely on. Turn questions into great experiences.', NOW()),
            ('UX/UI Designer', 'Budapest · Hybrid', 'Part-time / Full-time', 'Shape clear, human interfaces for complex HR workflows, working closely with developers and real users.', NOW())
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE job_position');
    }
}
