<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521193950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE enrollment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, enrolled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, course_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1A76ED395 ON enrollment (user_id)');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1591CC992 ON enrollment (course_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_enrollment_user_course ON enrollment (user_id, course_id)');
        $this->addSql('CREATE TABLE lesson_completion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, lesson_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35DF7EAFA76ED395 ON lesson_completion (user_id)');
        $this->addSql('CREATE INDEX IDX_35DF7EAFCDF80196 ON lesson_completion (lesson_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_completion_user_lesson ON lesson_completion (user_id, lesson_id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAFA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAFCDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE enrollment DROP CONSTRAINT FK_DBDCD7E1A76ED395');
        $this->addSql('ALTER TABLE enrollment DROP CONSTRAINT FK_DBDCD7E1591CC992');
        $this->addSql('ALTER TABLE lesson_completion DROP CONSTRAINT FK_35DF7EAFA76ED395');
        $this->addSql('ALTER TABLE lesson_completion DROP CONSTRAINT FK_35DF7EAFCDF80196');
        $this->addSql('DROP TABLE enrollment');
        $this->addSql('DROP TABLE lesson_completion');
    }
}
